# 设置服务器相关的配置
server:
  # 指定应用监听的端口号为8081
  port: 8081

spring:
  application:
    # 应用名称设置为hmdp
    name: hmdp
  datasource:
    # 数据库驱动类名，用于连接MySQL数据库
    driver-class-name: com.mysql.jdbc.Driver
    # MySQL数据库连接URL，包含数据库地址、端口、数据库名等信息。使用UTC时区且不启用SSL
    url: jdbc:mysql://127.0.0.1:3307/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    # TODO: 这里会被提交到 git 上，如何规避？
    password: gy123456
  redis:
    # Redis服务器的主机地址
    host: localhost
    # Redis服务器的端口号
    port: 6379
    # Redis服务器的访问密码
    password: ""
    eettuce:
      pool:
        # 连接池最大活跃连接数
        max-active: 10
        # 连接池中最大的空闲连接数
        max-idle: 10
        # 连接池中最小的空闲连接数
        min-idle: 1
        # 连接池中连接对象回收的时间间隔
        time-between-eviction-runs: 10s
  jackson:
    # JSON序列化时只包括非null字段
    default-property-inclusion: non_null

mybatis-plus:
  # MyBatis-Plus实体类别名扫描包路径
  type-aliases-package: com.hmdp.entity

logging:
  level:
    # 设置日志级别为debug，应用于com.hmdp包下的所有类
    com.hmdp: debug